In [2]:
import numpy as np
x =  np.arange(1,13).reshape((6,2)) 
def function1(x):
    return x
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [147]:
x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))
def function2(x):
    return x
x

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [148]:
a =  np.arange(35,1000,35)
def function3(a):
    return a
a

array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [149]:
arr = np.arange(9).reshape(3,3)
def function4(arr):
    return arr
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [170]:
z =np.zeros(20, dtype=np.int64).reshape(4,5)
def function5(z):
    return z
z


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [163]:
arr=np.zeros(10)
arr[5]=10
arr[8]=20
def function6(arr):
    return arr
arr

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

In [62]:
arrayid = np.zeros(4,  dtype=np.int64)
def function7(arrayid):
    return arrayid
arrayid

array([0, 0, 0, 0], dtype=int64)

In [194]:
x = np.full((2,5),6, dtype=np.int32)  
def function8(x):
    return x
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [195]:
array=np.arange(2,102,2)
def function9(array):
    return array
array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [214]:
arr = np.array([[3,4,5],[3,4,5],[3,4,5]])
brr = np.array([1,2,3])
subt =  arr-brr 
def function10(subt):
    return subt
subt

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [216]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ans = np.where(arr%2!=0,-1,arr)
def function11(ans):
    return ans
ans

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [218]:
arr = np.array([1,2,3])
ans = np.r_[np.repeat(arr, 3), np.tile(arr, 3)]
def function12(ans):
    return ans
ans

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [4]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])
ans = arr[(arr>5) & (arr<10)]
def function13(ans):
    return ans
ans


array([6, 9])

In [8]:
arr = np.arange(10, 34, 1).reshape(8,3)
arr
ans = arr.reshape(8,3)
ans
ans=np.split(ans,[1,3,5,7])
def function14(ans):
    return ans
ans


[array([[10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]]),
 array([[19, 20, 21],
        [22, 23, 24]]),
 array([[25, 26, 27],
        [28, 29, 30]]),
 array([[31, 32, 33]])]

In [33]:
arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
ans =  arr[np.argsort(arr[:, 1])]
def function(ans):
    return ans
ans

array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [36]:
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
ans = np.dstack((x, y))
def function16(ans):
    return ans
ans


array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [40]:
arr = np.arange(1, 10 * 10 + 1).reshape((10, 10))
ans = np.where(arr % 15 == 0, 'YES', 'NO')
def function17(ans):
    return ans
ans

array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')

In [52]:
piaic = np.arange(100)
students = np.array([5, 20, 50, 200, 301, 7001])
y =  np.intersect1d(piaic, students)
x=np.size(y)
def function18(x):
    return x
x

4

In [57]:
X =   np.arange(1,26).reshape(5,5) 
W =   X.copy() 
W =  np.swapaxes(W,0,1)
b=5
output =   (X*W)+b
def function19(output):
    return output
output

array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])

In [61]:
x = np.arange(1,11)
def abc(x):
    return x*2+3-2
    return abc(x)
abc(x)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])